/**
 * Vercel Build Script
 *
 * Reads environment variables and writes config.js
 * so the static site picks up keys at deploy time.
 *
 * Vercel runs:  node generate-config.js
 */

const fs = require("fs");

const config = {
  MAPBOX_ACCESS_TOKEN: process.env.MAPBOX_ACCESS_TOKEN || "",
  TMDB_V3_API_KEY: process.env.TMDB_V3_API_KEY || "",
  TMDB_READ_ACCESS_TOKEN: process.env.TMDB_READ_ACCESS_TOKEN || "",
  SUPABASE_URL: process.env.SUPABASE_URL || "",
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || "",
};

const content = `// Auto-generated by generate-config.js — do not edit
window.CINEMA_ATLAS_CONFIG = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync("config.js", content);
console.log("✅ config.js generated from environment variables");
